"use client";

import { useState, type FormEvent } from "react";
import { formatBRL } from "@/lib/money";
import { ProfessionalNegotiationForm } from "@/components/ProfessionalNegotiationForm";

const TABS = ["Visao Geral", "Relatorios", "Forma e Condicao", "Estatisticas", "Posicoes", "Contrato", "Relacionamentos", "Historico", "Reunioes", "Desenvolvimento"] as const;

export function PlayerProfile({ profile }: { profile: Record<string, any> }) {
  const [tab, setTab] = useState<(typeof TABS)[number]>("Visao Geral");
  const [meetingResult, setMeetingResult] = useState("");
  const [reportResult, setReportResult] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const player = profile.player;
  async function submitMeeting(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setMeetingResult(""); const form = new FormData(event.currentTarget);
    const response = await fetch(`/api/players/${player.id}/meetings`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject: form.get("subject"), text: form.get("text") }) });
    const body = await response.json(); setSubmitting(false);
    if (!response.ok) { setMeetingResult(body.message || "Nao foi possivel realizar a reuniao."); return; }
    setMeetingResult(body.reaction?.narrative || "Reuniao registrada."); event.currentTarget.reset();
  }
  async function requestReport(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setReportResult(""); const form = new FormData(event.currentTarget);
    const response = await fetch(`/api/players/${player.id}/reports`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ authorId: form.get("authorId") }) });
    const body = await response.json(); setSubmitting(false);
    if (!response.ok) { setReportResult(body.message || "Nao foi possivel produzir o relatorio."); return; }
    setReportResult("Relatorio registrado. Atualizando a leitura..."); window.location.reload();
  }
  return <>
    <section className="player-identity-band"><div className="squad-number">{player.squad_number || "-"}</div><div><p>{player.main_position} - {player.nationality}</p><h1>{player.known_as}</h1><span>{player.age} anos - pe {player.preferred_foot === "left" ? "esquerdo" : "direito"} - {player.height_cm} cm</span></div><div className="overall-score observed"><strong>{profile.reports.length}</strong><span>Relatorios</span></div></section>
    <nav className="profile-tabs" aria-label="Perfil do jogador">{TABS.map((item) => <button type="button" key={item} aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)}>{item}</button>)}</nav>
    <section className="profile-content">
      {tab === "Visao Geral" ? <><div className="sports-summary-band compact"><Metric label="Moral" value={profile.status?.morale} /><Metric label="Confianca" value={profile.status?.confidence} /><Metric label="Condicao" value={profile.status?.physical_condition} /><Metric label="Fadiga" value={profile.status?.fatigue} /><Metric label="Ritmo" value={profile.status?.match_fitness} /></div><div className="profile-columns"><section><h2>Recomendacao atual</h2><p>{profile.developmentAssessment}</p><p>{profile.potentialEstimate}</p></section><section><h2>Personalidade observada</h2><DataList empty="Perfil ainda em observacao." rows={profile.personality} /></section><section><h2>Disponibilidade</h2><p>Lesao: {labelize(profile.status?.injury_status || "available")}</p><p>Suspensao: {labelize(profile.status?.suspension_status || "available")}</p></section></div></> : null}
      {tab === "Relatorios" ? <div className="report-workspace"><form className="report-request" onSubmit={requestReport}><h2>Solicitar avaliacao</h2><label>Profissional<select name="authorId" required><option value="">Selecione</option>{profile.reportAuthors.map((item: any) => <option value={item.id} key={item.id}>{item.name} - {item.role_label}</option>)}</select></label><button type="submit" disabled={submitting || !profile.reportAuthors.length}>Produzir relatorio</button>{!profile.reportAuthors.length ? <p>Nao ha olheiro, analista ou tecnico ativo disponivel.</p> : null}{reportResult ? <p className="form-result">{reportResult}</p> : null}</form><section className="report-consensus"><h2>Consenso da comissao</h2>{profile.consensus.length ? profile.consensus.map((item: any) => <div className="consensus-row" key={item.category}><span>{labelize(item.category)}</span><strong>{item.consensus_label}</strong><small>faixa {item.lower_bound}-{item.upper_bound} - confianca {item.confidence}% - divergencia {item.divergence}</small></div>) : <p className="empty-state">Ainda nao ha consenso tecnico.</p>}</section><div className="report-list">{profile.reports.length ? profile.reports.map((report: any) => <article key={report.id}><header><div><span>{report.author_role}</span><h3>{report.author_name}</h3></div><b>{report.confidence_label}</b></header><p>{date(report.created_at)} - {ageLabel(report.age_status)} - precisao {report.precision}%</p><p>{report.summary}</p><div>{report.estimates.map((item: any) => <span key={item.category}>{labelize(item.category)}: {item.estimate_label} ({item.lower_bound}-{item.upper_bound})</span>)}</div><p><strong>Recomendacao:</strong> {report.recommendation}</p>{report.caveats.length ? <small>{report.caveats.join("; ")}</small> : null}</article>) : <p className="empty-state">Nenhum relatorio produzido.</p>}</div></div> : null}
      {tab === "Forma e Condicao" ? <div className="profile-columns"><section><h2>Estado atual</h2><Metric label="Forma" value={(profile.status?.form_rating || 0) * 10} /><Metric label="Prontidao" value={profile.status?.sharpness} /><Metric label="Carga" value={profile.status?.training_load} /></section><section><h2>Ocorrencias</h2><p>{profile.injuries.length ? `${profile.injuries.length} lesao(oes) no historico.` : "Sem lesoes registradas."}</p><p>{profile.suspensions.length ? `${profile.suspensions.length} suspensao(oes) no historico.` : "Sem suspensoes registradas."}</p></section></div> : null}
      {tab === "Estatisticas" ? <DataList empty="Nenhuma estatistica de temporada registrada." rows={profile.stats.map((item: any) => `${item.season} - ${item.competition}: ${item.appearances} jogos, ${item.goals} gols, nota ${item.average_rating}`)} /> : null}
      {tab === "Posicoes" ? <div className="profile-columns"><section><h2>Posicoes observadas</h2>{profile.positions.map((item: any) => <div className="attribute-row" key={item.position}><span>{item.position}</span><strong>{item.assessment}</strong></div>)}</section><section><h2>Funcoes observadas</h2>{profile.roles.map((item: any) => <div className="attribute-row" key={item.role}><span>{labelize(item.role)}</span><strong>{item.assessment}</strong></div>)}</section></div> : null}
      {tab === "Contrato" ? <><div className="profile-columns">{profile.contracts.map((item: any) => <section key={item.id}><h2>{item.contract_type === "trial" ? "Contrato de teste" : item.status === "active" ? "Contrato atual" : "Contrato"}</h2><p>{date(item.contract_start)} a {date(item.contract_end)}</p><p>Salario mensal: {formatBRL(item.monthly_salary)}</p><p>Papel prometido: {labelize(item.squad_role_promised)}</p><p>Clausula: {item.release_clause == null ? "Nao aplicavel" : formatBRL(item.release_clause)}</p>{item.contract_type === "trial" ? <><p>Sem renovacao automatica, transferencia, emprestimo ou multa.</p><p className="trial-deadline-alert">{trialAlert(item.contract_end)}</p></> : null}</section>)}</div>{profile.contracts.some((item: any) => item.contract_type === "trial" && item.status === "active") ? <ProfessionalNegotiationForm playerId={player.id} /> : null}</> : null}
      {tab === "Relacionamentos" ? <DataList empty="Relacionamentos ainda em observacao." rows={profile.relationships.map((item: any) => `${labelize(item.target_type)} - afinidade ${item.affinity}, confianca ${item.trust}, respeito ${item.respect}, tensao ${item.tension}`)} /> : null}
      {tab === "Historico" ? <><DataList empty="Sem passagens anteriores registradas." rows={profile.history.map((item: any) => `${item.club_name} - ${item.season_start}${item.season_end ? `-${item.season_end}` : ""}`)} /><h2>Memorias</h2><DataList empty="Nenhuma memoria estruturada." rows={profile.memories.map((item: any) => `${date(item.created_at)} - ${item.summary}`)} /></> : null}
      {tab === "Reunioes" ? <div className="meeting-layout"><form className="player-meeting-form" onSubmit={submitMeeting}><h2>Reuniao particular</h2><label>Assunto<input name="subject" required minLength={3} maxLength={180} /></label><label>Mensagem<textarea name="text" required minLength={3} maxLength={5000} /></label><button type="submit" disabled={submitting}>{submitting ? "Processando..." : "Conversar com jogador"}</button>{meetingResult ? <p className="form-result" role="status">{meetingResult}</p> : null}</form><section><h2>Reacoes anteriores</h2><DataList empty="Nenhuma reuniao anterior." rows={profile.meetings.map((item: any) => `${date(item.created_at)} - ${item.structured_reaction?.narrative || labelize(item.classification)}`)} /></section></div> : null}
      {tab === "Desenvolvimento" ? <div className="profile-columns"><section><h2>Avaliacao</h2><p>{profile.developmentAssessment}</p><p>O potencial real permanece oculto e so pode ser aproximado por relatorios sucessivos.</p></section><section><h2>Treinos recentes</h2><DataList empty="Ainda sem historico diario." rows={profile.training.map((item: any) => `${date(item.training_date)} - ${item.focus} - carga ${item.load}`)} /></section></div> : null}
    </section>
  </>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="profile-metric"><span>{label}</span><strong>{Math.round(Number(value || 0))}</strong><div><i style={{ width: `${Math.max(0, Math.min(100, Number(value || 0)))}%` }} /></div></div>; }
function DataList({ rows, empty }: { rows: string[]; empty: string }) { return rows.length ? <ul className="data-list">{rows.map((row, index) => <li key={`${row}-${index}`}>{row}</li>)}</ul> : <p className="empty-state">{empty}</p>; }
function labelize(value: string) { return String(value).replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function date(value: string) { return new Intl.DateTimeFormat("pt-BR").format(new Date(value.length === 10 ? `${value}T12:00:00` : value)); }
function ageLabel(value: string) { return ({ current: "Atual", update_needed: "Precisa atualizar", outdated: "Desatualizado", unreliable: "Pouco confiavel" } as Record<string,string>)[value] || value; }
function trialAlert(value:string){const days=Math.max(0,Math.ceil((new Date(`${value}T23:59:59`).getTime()-Date.now())/86_400_000));const threshold=[15,7,3,1].find((item)=>days<=item);return threshold?`Alerta: restam ${days} dia(s) para o encerramento automatico.`:`Restam ${days} dia(s) de avaliacao.`;}
